; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-wroom]
platform = espressif32
board = upesy_wroom
framework = arduino
monitor_speed = 115200
lib_dir = lib/library
build_flags = 
	-Ofast
	-DI2S_WS=25
	-DI2S_SD=33
	-DI2S_SCK=26
	-DI2S_PORT=I2S_NUM_0
	-DONBOARD_LED_PIN=2
	-DCHANNEL_FORMAT=I2S_CHANNEL_FMT_ONLY_RIGHT
monitor_filters = esp32_exception_decoder

[env:esp32-wroom-with-motors]
platform = espressif32
board = upesy_wroom
framework = arduino
monitor_speed = 115200
lib_dir = lib/library
build_flags = 
	-Ofast
	-DI2S_WS=25
	-DI2S_SD=33
	-DI2S_SCK=26
	-DI2S_PORT=I2S_NUM_0
	-DINCLUDE_MOTORS
	-DLEFT_MOTOR_PIN=14
	-DRIGHT_MOTOR_PIN=12
	-DONBOARD_LED_PIN=2
	-DCHANNEL_FORMAT=I2S_CHANNEL_FMT_ONLY_RIGHT
monitor_filters = esp32_exception_decoder

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitm-1
framework = arduino
build_flags = 
	-Ofast
  	-DARDUINO_USB_MODE=1
  	-DARDUINO_USB_CDC_ON_BOOT=1
	-DI2S_WS=11
	-DI2S_SD=13
	-DI2S_SCK=12
	-DI2S_PORT=I2S_NUM_1
	-DONBOARD_LED_PIN=2
	-DCHANNEL_FORMAT=I2S_CHANNEL_FMT_ONLY_LEFT
monitor_filters = esp32_exception_decoder
board_upload.flash_size = 4MB 
board_build.partitions = default.csv