; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


[env:esp32-wroom-ros]
platform = espressif32
board = upesy_wroom
framework = arduino
monitor_speed = 115200
lib_dir = lib/library
build_flags = 
	-DWIFI
	-Ofast
	-DI2S_WS=25
	-DI2S_SD=33
	-DI2S_SCK=26
	-DI2S_PORT=I2S_NUM_0
	-DONBOARD_LED_PIN=2
monitor_filters = esp32_exception_decoder

lib_deps =
    https://github.com/AvansMechatronica/micro_ros_platformio
    WiFi
    ESP32Async/ESPAsyncWebServer

; Use WiFi transport for micro-ROS
board_microros_transport = wifi 
;board_microros_transport = serial